### ISSUE TITLE
timeout facing issue 

### ISSUE THREAD

**Issue by appasaheb4** [lihaibh/mongodb-snapshot#35]
{
  error: MongoServerSelectionError: getaddrinfo ENOTFOUND cluster0.wcvye.mongodb.net
      at Timeout._onTimeout (/Users/appasaheb4/Documents/project/backend/limsplus-website-service/node_modules/mongodb-snapshot/node_modules/mongodb/lib/core/sdam/topology.js:438:30)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7) {
    reason: TopologyDescription {
      type: 'Single',
      setName: null,
      maxSetVersion: null,
      maxElectionId: null,
      servers: [Map],
      stale: false,
      compatible: true,
      compatibilityError: null,
      logicalSessionTimeoutMinutes: null,
      heartbeatFrequencyMS: 10000,
      localThresholdMS: 15,
      commonWireVersion: null
    }
  }
}
<img width="599" alt="Screenshot 2022-10-24 at 1 56 22 PM" src="https://user-images.githubusercontent.com/24726539/197482012-1e7bd1f3-2f51-421b-835c-249cc9decba2.png">

**Comment by lihaibh** [comment]
It looks like connection problem. The connection fails, it didn't even start the transfer.
